### PR TITLE
Feature/onclick popup

### LINKED ISSUE #66: Introduce onClick hover/modal
So far TGVE has been relying on `hover`. Having both options will be useful to variety of projects.

### PR DESCRIPTION
**Pull request by nbarlowATI**
* Create new component `Popup`, based on existing `Tooltip`.
* Add new function `_renderPopup` in `Welcome.js`, similar to `_renderTooltip` but called by `onClick`.
* Refactor out `renderTooltip` and `listPropsAndValues` from the `Tooltip` class into standalone functions, and put them into `utils.py`.

Still to be done:
 - [x] Styling for popup
 - [x] Remove debug console logs

### CODE REVIEW

**Comment by layik** [comment]
I meant to add one or two commits here @nbarlowATI. Mostly design and just going over the baseui and also testing mobile view and how it works with `sidebar` when open. I am sure there is more work but this would address the open issue.

**Comment by layik** [comment]
- [x] the two components are almost identical, see commit sent. So should be one and switch based on a flag.
- [x] requires DeckGL api change for grid, hex which means we do not show properties of hovered point data currently
- [x]  Close button (design)
- [ ] Final checks

**Comment by layik** [comment]
@nbarlowATI please have a little play with it. I think we can merge but may be one or two final tweaks. Right now, if user hovers and a popup is on, it behaves like user wants to compare/explore? Could make popup disappear if user hovers. As you know this is not the case on mobile devices.

**Comment by layik** [comment]
Maybe a comment somewhere about `absolute` and `inherit`.

**Comment by nbarlowATI** [comment]
Hi @layik I just had a play, and I think it's good like this! :)
FWIW in my opinion, better for the popup not to disappear when the user hovers - I think if the user clicks on a point it's because they want to look at it, so it could potentially be annoying if it disappeared if they accidentally hovered over something else...

**Comment by layik** [comment]
Thanks Nick. Agreed. Shall we merge?

**Pull request merged**
